protected/models/Subdepartment.php
<?php

/**
 * This is the model class for table "{{subdepartment}}".
 *
 * The followings are the available columns in table '{{subdepartment}}':
 * @property string $id
 * @property string $deptId
 * @property string $name
 * @property string $name_bd
 * @property string $status
 * @property string $crAt
 * @property string $crBy
 * @property string $moAt
 * @property string $moBy
 * @property string $rank
 *
 * The followings are the available model relations:
 * @property Items[] $items
 * @property Department $dept
 * @property User $crBy0
 * @property User $moBy0
 */
class Subdepartment extends CActiveRecord
{
	const STATUS_ACTIVE=1;
	const STATUS_INACTIVE=2;
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Subdepartment the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{subdepartment}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
            array('deptId, name, status', 'required'),
        	array('deptId+name', 'application.extensions.uniqueMultiColumnValidator.uniqueMultiColumnValidator'),
			array('deptId, rank', 'length', 'max'=>10),
			array('name, name_bd', 'length', 'max'=>50),
			array('status', 'length', 'max'=>11),
			array('crBy, moBy', 'length', 'max'=>20),
			array('crAt, moAt', 'safe'),
			array('price', 'safe'),
			array('retrieve_previous_price', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, deptId, name, status, crAt, crBy, moAt, moBy, rank', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'dept' => array(self::BELONGS_TO, 'Department', 'deptId'),
			'crBy0' => array(self::BELONGS_TO, 'User', 'crBy'),
			'moBy0' => array(self::BELONGS_TO, 'User', 'moBy'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'deptId' => 'Category',
			'price' => 'Price',
			'retrieve_previous_price' => 'Do you want to retrieve previous price? Yes',
			'name' => 'Sub Category',
			'name_bd' => 'Name (বাংলা)',
			'status' => 'Status',
			'crAt' => 'Cr At',
			'crBy' => 'Cr By',
			'moAt' => 'Mo At',
			'moBy' => 'Mo By',
			'rank' => 'Rank',
		);
	}
    
    /*-----------Save before functionality------------*/
	protected function beforeSave()
	{
		if(parent::beforeSave())
		{
			if($this->isNewRecord)
			{
				$this->crAt=date("Y-m-d H:i:s");
				$this->crBy=Yii::app()->user->id;	
			}
			return true;
		}
		else
			return false;
	}
    
    //-----------get all record by status as dropdown--------//
    public static function getAllSubdepartment($isActive)
	{      
		 return CHtml::listData(self::model()->findAll(array('condition'=>'status=:status', 'params'=>array(':status'=>$isActive))), 'id', 'name');      
	}
	
	// get all subdept by dept
    public static function getAllSubDeptByDept($deptId,$isActive)
    {
        return self::model()->findAll(array('condition'=>'deptId=:deptId and status=:status', 'params'=>array(':deptId'=>$deptId,':status'=>$isActive)));
    }

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('deptId',$this->deptId);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('status',$this->status,true);
		$criteria->compare('crAt',$this->crAt,true);
		$criteria->compare('crBy',$this->crBy,true);
		$criteria->compare('moAt',$this->moAt,true);
		$criteria->compare('moBy',$this->moBy,true);
		$criteria->compare('rank',$this->rank,true);

		return new CActiveDataProvider($this, array(
        	'pagination'=>array(
				//
				// please check how we get the
				// the pageSize from user's state
				'pageSize'=> Yii::app()->user->getState('pageSize',
				//
				// we have previously set defaultPageSize
				// on the params section of our main.php config file
				Yii::app()->params['defaultPageSize']),
			),
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/SubdepartmentController.php
<?php

/* * *******************************************************
  -*- File: SubdepartmentController.php
  -*- Author: Md.kamruzzaman<kzaman.badal@gmail.com>
  -*- Date: 2014.03.06
  -*- Position:  protected/controller
  -*- YII-*- version 1.1.13
  /******************************************************** */

class SubdepartmentController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/adminColumn', meaning
     * using two-column layout. See 'protected/views/layouts/adminColumn.php'.
     */
    public $metaTitle = NULL;
    public $metaKeywords = NULL;
    public $metaDescriptions = NULL;
    public $defaultAction = 'index';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $msg = '';
        $model = new Subdepartment;

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if (isset($_POST['Subdepartment'])) {
            $model->attributes = $_POST['Subdepartment'];
            if ($model->save()) {
                $msg = "Sub Category  Saved Successfully";
                $model = new Subdepartment;
                //$this->redirect(array('view','id'=>$model->id));
                if (!empty($_POST['Subdepartment']['price'])){
                    echo "<pre>";
                    print_r($model);
                    exit();
                }

            }
        }

        $this->render('_form', array(
            'model' => $model,
            'msg' => $msg,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $msg = '';
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if (isset($_POST['Subdepartment'])) {
            $model->attributes = $_POST['Subdepartment'];
            if ($model->save())
                $msg = "Sub Category  Updated Successfully";
            //$this->redirect(array('admin'));

            //Update Price After Import Previous Price
            if (!empty($_POST['Subdepartment']['price']) && $_POST['Subdepartment']['retrieve_previous_price']==0){

                $sqlItems = "SELECT * from pos_items  where variation=0 and subdeptId='".$model->id."'";
                $modelItemData = Yii::app()->db->createCommand($sqlItems)->queryAll();
                $backupDataArray=[];
                $variationsDataArray=[];


                foreach ($modelItemData as $modelItems){
                    $backupDataArray[]=[
                        'itemId'=>$modelItems['id'],
                        'subdeptId'=>$model->id,
                        'sellPrice'=>$modelItems['sellPrice']
                    ];
                    $updateSql="UPDATE `pos_items` SET `sellPrice`='".$_POST['Subdepartment']['price']."' WHERE id='".$modelItems['id']."'";
                    Yii::app()->db->createCommand($updateSql)->execute();

                    if ($modelItems['variation_type']==2){

                        $sqlVariationsItems = "SELECT * from pos_items  where  variation='".$modelItems['id']."'";
                        $modelVariationsItem = Yii::app()->db->createCommand($sqlVariationsItems)->queryAll();

                        foreach ($modelVariationsItem as $variationData){
                            $varationsIdAndPriceSql="SELECT * from pos_items_variation WHERE item_id='".$variationData['id']."'";
                            $modelSpecialGetingVariaitonId = Yii::app()->db->createCommand($varationsIdAndPriceSql)->queryRow();

                            $variationsDataArray[]=[
                                'variationsId'=>$modelSpecialGetingVariaitonId['id'],
                                'sellPrice'=>$variationData['sellPrice']
                            ];

                            $updateVariationsSql11="UPDATE `pos_items_variation` SET `sell_price`='".$_POST['Subdepartment']['price']."' WHERE item_id='".$variationData['id']."'";
                            Yii::app()->db->createCommand($updateVariationsSql11)->execute();
                        }

                        $updateVariationsSql="UPDATE `pos_items` SET `sellPrice`='".$_POST['Subdepartment']['price']."' WHERE variation='".$modelItems['id']."'";
                        Yii::app()->db->createCommand($updateVariationsSql)->execute();



                    }
                }

                $get_company_infoJE = json_encode($backupDataArray);
                $getCompanyInfofileW = fopen("itemPrice.txt", "w") or die("Unable to open file!");
                fwrite($getCompanyInfofileW, $get_company_infoJE);

                $variationInfo = json_encode($variationsDataArray);
                $getVariationInfo = fopen("variationPrice.txt", "w") or die("Unable to open file!");
                fwrite($getVariationInfo, $variationInfo);

            }

            //Retrive Price After Import Previous Price
            if (!empty($_POST['Subdepartment']['retrieve_previous_price']) && $_POST['Subdepartment']['retrieve_previous_price']==1){
                $getPriceList = array_values((array)$this->getTextJsonFile('itemPrice'));
                if ($getPriceList) {
                    foreach ($getPriceList as $getPriceListItems) {
                        $updateSql = "UPDATE `pos_items` SET `sellPrice`='" . $getPriceListItems->sellPrice . "' WHERE id='" . $getPriceListItems->itemId . "'";
                        Yii::app()->db->createCommand($updateSql)->execute();
                        $msg = "Retrieve Price  Updated Successfully";
                    }
                }

                $getVariationPriceList = array_values((array)$this->getTextJsonFile('variationPrice'));
                if ($getVariationPriceList) {
                    foreach ($getVariationPriceList as $getVariationPriceListItems) {
                        $updateVariationDataSql = "UPDATE `pos_items_variation` SET `sell_price`='".$getVariationPriceListItems->sellPrice."' WHERE id='".$getVariationPriceListItems->variationsId."'";
                        Yii::app()->db->createCommand($updateVariationDataSql)->execute();
                        $msg = "Retrieve Price  Updated Successfully";
                    }
                }

            }

        }

        $this->render('_form', array(
            'model' => $model,
            'msg' => $msg,
        ));
    }

    public function getTextJsonFile($fileName){

        $getCompanyInfofileR    = fopen($fileName.".txt", "r") or die("Unable to open file!");
        $getCompanyInfofileV    = fread($getCompanyInfofileR,filesize($fileName.".txt"));

        return json_decode($getCompanyInfofileV);
    }


    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Subdepartment');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        if (isset($_GET['pageSize'])) {
            //
            // pageSize will be set on user's state
            Yii::app()->user->setState('pageSize', (int) $_GET['pageSize']);
            //
            // unset the parameter as it
            // would interfere with pager
            // and repetitive page size change
            unset($_GET['pageSize']);
        }

        $model = new Subdepartment('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Subdepartment']))
            $model->attributes = $_GET['Subdepartment'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Subdepartment the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Subdepartment::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Subdepartment $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'subdepartment-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/subdepartment/19.07.20_form.php
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>Home
        <i class="icon-angle-right"></i>
    </li>
    <li>Back Store
	 <i class="icon-angle-right"></i>
	</li>
	 <li>Sub department
	</li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'subdepartment-form',
	'enableAjaxValidation'=>true,
)); ?>

<?php echo $form->errorSummary($model); ?>

<?php if(!empty($msg)) :?>
<div class="notification note-success">
	<p><?php echo $msg;?></p>
</div>
<?php else :?>
<div class="notification note-error">
	<p>All star marked <span class="required">*</span> fields are mandatory, please fill up all mandatory fields.</p>
</div>
<?php endif;?>
<div class="tabbable tabbable-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1_1" data-toggle="tab"><?php echo $model->isNewRecord ? 'Add' : 'Update';?>&nbsp; Sub department</a></li>
    </ul>
	<div class="tab-content">
		<div class="tab-pane active span4" id="tab_1_1">
			 <div class="row">
				<?php echo $form->labelEx($model,'deptId'); ?>
				<?php echo $form->dropDownList($model,'deptId', Department::getAllDepartment(Department::STATUS_ACTIVE), array('class'=>'m-wrap combo combobox','prompt'=>'Select Department')); ?>
				<?php echo $form->error($model,'deptId'); ?>
			</div>
			<div class="row">
				<?php echo $form->labelEx($model,'name'); ?>
				<?php echo $form->textField($model,'name',array('class'=>'m-wrap span','size'=>50,'maxlength'=>50)); ?>
				<?php echo $form->error($model,'name'); ?>
			</div>
            <div class="row">
                <?php echo $form->labelEx($model,'name_bd'); ?>
                <?php echo $form->textField($model,'name_bd',array('class'=>'m-wrap span','size'=>50,'maxlength'=>50)); ?>
                <?php echo $form->error($model,'name_bd'); ?>
            </div>
			<div class="row">
				<?php echo $form->labelEx($model,'status'); ?>
				<?php echo $form->dropDownList($model,'status', Lookup::items('Status'), array('options'=>array(User::STATUS_ACTIVE=>array('selected'=>'selected')),'class'=>'m-wrap span','prompt'=>'Select Status')); ?>
				<?php echo $form->error($model,'status'); ?>
			</div>
        </div>    
    </div>
	<div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Save' : 'Update', array('class'=>'btn blue')); ?>
    </div>
</div>
<?php $this->endWidget(); ?>
    
</div> <!-- form -->   

protected/views/subdepartment/_form.php
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<style>
    .row.checkboxLabel label {
        margin-top: -1.5em;
        margin-left: 23px;
    }
</style>
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>Home
        <i class="icon-angle-right"></i>
    </li>
    <li>Back Store
	 <i class="icon-angle-right"></i>
	</li>
	 <li>Sub department
	</li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'subdepartment-form',
	'enableAjaxValidation'=>true,
)); ?>

<?php echo $form->errorSummary($model); ?>

<?php if(!empty($msg)) :?>
<div class="notification note-success">
	<p><?php echo $msg;?></p>
</div>
<?php else :?>
<div class="notification note-error">
	<p>All star marked <span class="required">*</span> fields are mandatory, please fill up all mandatory fields.</p>
</div>
<?php endif;?>
<div class="tabbable tabbable-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1_1" data-toggle="tab"><?php echo $model->isNewRecord ? 'Add' : 'Update';?>&nbsp; Sub department</a></li>
    </ul>
	<div class="tab-content">
		<div class="tab-pane active span4" id="tab_1_1">
			 <div class="row">
				<?php echo $form->labelEx($model,'deptId'); ?>
				<?php echo $form->dropDownList($model,'deptId', Department::getAllDepartment(Department::STATUS_ACTIVE), array('class'=>'m-wrap combo combobox','prompt'=>'Select Department')); ?>
				<?php echo $form->error($model,'deptId'); ?>
			</div>
			<div class="row">
				<?php echo $form->labelEx($model,'name'); ?>
				<?php echo $form->textField($model,'name',array('class'=>'m-wrap span','size'=>50,'maxlength'=>50)); ?>
				<?php echo $form->error($model,'name'); ?>
			</div>
            <div class="row">
                <?php echo $form->labelEx($model,'name_bd'); ?>
                <?php echo $form->textField($model,'name_bd',array('class'=>'m-wrap span','size'=>50,'maxlength'=>50)); ?>
                <?php echo $form->error($model,'name_bd'); ?>
            </div>

			<div class="row">
				<?php echo $form->labelEx($model,'status'); ?>
				<?php echo $form->dropDownList($model,'status', Lookup::items('Status'), array('options'=>array(User::STATUS_ACTIVE=>array('selected'=>'selected')),'class'=>'m-wrap span','prompt'=>'Select Status')); ?>
				<?php echo $form->error($model,'status'); ?>
			</div>
            <?php
            if (!$model->isNewRecord ){
            ?>
            <div class="row">
                <?php echo $form->labelEx($model,'price'); ?>
                <?php echo $form->textField($model,'price',array('class'=>'m-wrap span','size'=>50,'maxlength'=>50)); ?>
                <?php echo $form->error($model,'price'); ?>
            </div>
            <div class="row checkboxLabel" style="font-size: 16px;margin-top: 17px;width: 500px;">
                <?php echo $form->checkBox($model,'retrieve_previous_price'); ?>
                <?php echo $form->labelEx($model,'retrieve_previous_price'); ?>
                <?php echo $form->error($model,'retrieve_previous_price'); ?>
            </div>
            <?php }?>
        </div>    
    </div>
	<div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Save' : 'Update', array('class'=>'btn blue')); ?>
    </div>
</div>
<?php $this->endWidget(); ?>
    
</div> <!-- form -->   

protected/views/subdepartment/_search.php
<?php
/* @var $this SubdepartmentController */
/* @var $model Subdepartment */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('class'=>'m-wrap large','size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'deptId'); ?>
		<?php echo $form->textField($model,'deptId',array('class'=>'m-wrap large','size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('class'=>'m-wrap large','size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->dropDownList($model,'status', Lookup::items('Status'), array('options'=>array(User::STATUS_ACTIVE=>array('selected'=>'selected')),'class'=>'m-wrap large','prompt'=>'Select Status')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'crAt'); ?>
		<?php echo $form->textField($model,'crAt',array('class'=>'m-wrap large')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'crBy'); ?>
		<?php echo $form->textField($model,'crBy',array('class'=>'m-wrap large','size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'moAt'); ?>
		<?php echo $form->textField($model,'moAt',array('class'=>'m-wrap large')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'moBy'); ?>
		<?php echo $form->textField($model,'moBy',array('class'=>'m-wrap large','size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'rank'); ?>
		<?php echo $form->textField($model,'rank',array('class'=>'m-wrap large','size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/subdepartment/_view.php
<?php
/* @var $this SubdepartmentController */
/* @var $data Subdepartment */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('deptId')); ?>:</b>
	<?php echo CHtml::encode($data->deptId); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('crAt')); ?>:</b>
	<?php echo CHtml::encode($data->crAt); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('crBy')); ?>:</b>
	<?php echo CHtml::encode($data->crBy); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('moAt')); ?>:</b>
	<?php echo CHtml::encode($data->moAt); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('moBy')); ?>:</b>
	<?php echo CHtml::encode($data->moBy); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('rank')); ?>:</b>
	<?php echo CHtml::encode($data->rank); ?>
	<br />

	*/ ?>

</div>

protected/views/subdepartment/admin.php
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>Home
        <i class="icon-angle-right"></i>
    </li>
    <li>Back Store <i class="icon-angle-right"></i></li>
    <li>Sub Department <i class="icon-angle-right"></i></li>
    <li>Manage Sub Department</li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->

<?php CHtml::link('Add Subdepartment', array('subdepartment/create'), array('class'=>'btn light', 'style'=>'float:right;margin-left:10px;'));?>

<div class="form">
<?php $pageSize=Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']); ?>
<?php $this->widget('bootstrap.widgets.TbExtendedGridView', array(
	'id'=>'subdepartment-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
    'type' => 'striped bordered condensed',
    'template' => '{summary}{items}{pager}',
    'pager'=> array('header'=>'','class'=> 'MyLinkPager'),
	'columns'=>array(
		array('header'=>'Sl.',
				 'value'=>'$row+1',
		),
		array('name'=>'deptId',
			 'value'=>'!empty($data->dept->name)?$data->dept->name:null',
			 'filter'=>Department::getAllDepartment(Department::STATUS_ACTIVE),
			 //'filter'=>CHtml::activeDropDownList($model, 'deptId',Department::getAllDepartment(Department::STATUS_ACTIVE), array('class'=>'m-wrap combo combobox','prompt'=>'Select Supplier')),
		),
		'name',
		array('name'=>'status',
				 'value'=>'Lookup::item("Status", $data->status)',
				 'filter'=>Lookup::items('Status'),
		),
		'rank',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
            'viewButtonImageUrl' => Yii::app()->theme->baseUrl.'/images/gridview/view.png',
			'updateButtonImageUrl' => Yii::app()->theme->baseUrl.'/images/gridview/update.png',
			'deleteButtonImageUrl' => Yii::app()->theme->baseUrl.'/images/gridview/delete.png',
            'header'=>CHtml::dropDownList('pageSize',
		        $pageSize,
		        array(5=>5,10=>10,20=>20,50=>50,100=>100),
		        array(
		       //
		       // change 'user-grid' to the actual id of your grid!!
		        'onchange'=>
		        "$.fn.yiiGridView.update('subdepartment-grid',{ data:{pageSize: $(this).val() }})",
		    )),
		),
	),
)); ?>
</div>

protected/views/subdepartment/create.php
<?php
/* @var $this SubdepartmentController */
/* @var $model Subdepartment */

$this->breadcrumbs=array(
	'Subdepartments'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Subdepartment', 'url'=>array('index')),
	array('label'=>'Manage Subdepartment', 'url'=>array('admin')),
);
?>

<h1>Create Subdepartment</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/subdepartment/index.php
<?php
/* @var $this SubdepartmentController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Subdepartments',
);

$this->menu=array(
	array('label'=>'Create Subdepartment', 'url'=>array('create')),
	array('label'=>'Manage Subdepartment', 'url'=>array('admin')),
);
?>

<h1>Subdepartments</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>