protected/controllers/CompanyController.php
<?php
/*********************************************************
-*- logo: CompanyController.php
-*- Author: Md.kamruzzaman<kzaman.badal@gmail.com>
-*- Date: 2014.02.24
-*- Position:  protected/controller
-*- YII-*- version 1.1.13
/*********************************************************/

class CompanyController extends Controller
{
    /**
     * @var string the default layout for the @views. Defaults to '//layouts/adminColumn', meaning
     * using two-column layout. See 'protected/@views/layouts/adminColumn.php'.
     */
    public $metaTitle 	 	 = NULL;
    public $metaKeywords 	 = NULL;
    public $metaDescriptions = NULL;
    public $defaultAction = 'index';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $msg = '';
        $model=new Company;

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if(isset($_POST['Company']))
        {
            $model->attributes=$_POST['Company'];

            if (CUploadedFile::getInstance($model,'logo') && CUploadedFile::getInstance($model,'favicon'))
            {
                $uploaddir = dirname(Yii::app()->request->scriptFile) . '/media/system/';

                // favicon
                $explogonameIco = CUploadedFile::getInstance($model,'favicon');
                $newfaviconname = date("YmdHis") .'_'. $explogonameIco;
                $favicon = $uploaddir.'/'.$newfaviconname;
                $model->favicon = '/media/system/'.$newfaviconname;

                // logo
                $explogonameLogo = CUploadedFile::getInstance($model,'logo');
                $newlogoname = date("YmdHis") .'_'. $explogonameLogo;
                $logo = $uploaddir.'/'.$newlogoname;
                $model->logo = '/media/system/'.$newlogoname;
            }
            if($model->save())
            {
                // server subDomain processing

                // logo resize with favicon upload
                $explogonameIco->saveAs($favicon);
                if(CUploadedFile::getInstance($model,'logo') && $explogonameLogo->saveAs($logo))  {
                    $image = Yii::app()->image->load($logo);
                    //$image->resize(150, 110)->quality(100)->sharpen(20);
                    $image->save();
                }
                $msg = "Company Added Successfully";
                $model=new Company;
            }
        }

        $this->render('_form',array(
            'model'=>$model,
            'msg'=>$msg,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $msg = '';
        $model=$this->loadModel($id);
        $modellogo = $model->logo;
        $modelfavicon = $model->favicon;

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if(isset($_POST['Company']))
        {
            $model->attributes=$_POST['Company'];
            $uploaddir = dirname(Yii::app()->request->scriptFile) . '/media/system/';

            // favicon processing
            if (CUploadedFile::getInstance($model,'favicon')) {
                $explogonameIco = CUploadedFile::getInstance($model,'favicon');
                $newfaviconname = date("YmdHis") .'_'. $explogonameIco;
                $favicon = $uploaddir.'/'.$newfaviconname;
                $model->favicon = '/media/system/'.$newfaviconname;
                if($explogonameIco->saveAs($favicon))
                {
                    //-------delete previous------//
                    if(file_exists($modelfavicon)) unlink($modelfavicon);
                }
            }
            else $model->favicon = $modelfavicon;

            // logo processing
            if (CUploadedFile::getInstance($model,'logo')) {
                $explogonameLogo = CUploadedFile::getInstance($model,'logo');
                $newlogoname = date("YmdHis") .'_'. $explogonameLogo;
                $logo = $uploaddir.'/'.$newlogoname;
                $model->logo = '/media/system/'.$newlogoname;
            }
            else $model->logo = $modellogo;

            if($model->save()) {
                if(CUploadedFile::getInstance($model,'logo') && $explogonameLogo->saveAs($logo))  {
                    //-------delete previous------//
                    if(file_exists($modellogo)) unlink($modellogo);
                    $image = Yii::app()->image->load($logo);
                    //$image->resize(150, 110)->quality(100)->sharpen(20);
                    $image->save();
                }
                $msg = "Company Updated Successfully";
            }
        }

        $this->render('_form',array(
            'model'=>$model,
            'msg'=>$msg,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $model = $this->loadModel($id);
        if(file_exists(dirname(Yii::app()->request->scriptFile).$model->favicon)) unlink(dirname(Yii::app()->request->scriptFile).$model->favicon); //--favicon delete
        if(file_exists(dirname(Yii::app()->request->scriptFile).$model->logo)) unlink(dirname(Yii::app()->request->scriptFile).$model->logo); //--logo delete
        $model->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider=new CActiveDataProvider('Company');
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        if (isset($_GET['pageSize'])) {
            //
            // pageSize will be set on user's state
            Yii::app()->user->setState('pageSize',(int)$_GET['pageSize']);
            //
            // unset the parameter as it
            // would interfere with pager
            // and repetitive page size change
            unset($_GET['pageSize']);
        }

        $model=new Company('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Company']))
            $model->attributes=$_GET['Company'];

        $this->render('admin',array(
            'model'=>$model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Company the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=Company::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Company $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='company-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/views/company/_form.php
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>Home
        <i class="icon-angle-right"></i>
    </li>
    <li>Settings
	 <i class="icon-angle-right"></i>
	</li>
	 <li>Company
	</li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'company-form',
	'enableAjaxValidation'=>true,
	'htmlOptions'=>array('enctype'=>'multipart/form-data'),
)); ?>

<?php echo $form->errorSummary($model); ?>

<?php if(!empty($msg)) :?>
<div class="notification note-success">
	<p><?php echo $msg;?></p>
</div>
<?php else :?>
<div class="notification note-error">
	<p>All star marked <span class="required">*</span> fields are mandatory, please fill up all mandatory fields.</p>
</div>
<?php endif;?>
<div class="tabbable tabbable-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1_1" data-toggle="tab"><?php echo $model->isNewRecord ? 'Add' : 'Update';?>&nbsp; Company</a></li>
    </ul>

	<div class="tab-content">
		<div class="tab-pane active" id="tab_1_1">
            <div class="row">
                <div class="span5">
                    <?php echo $form->labelEx($model,'orgIdPrefix'); ?>
                    <?php echo $form->textField($model,'orgIdPrefix',array('class'=>'m-wrap large','size'=>5,'maxlength'=>5)); ?>
                    <?php echo $form->error($model,'orgIdPrefix'); ?>                    
                </div>  
                <?php if(isset(Yii::app()->user->isSuperAdmin) && !empty(Yii::app()->user->isSuperAdmin)) : ?>
                <div class="span4">
                    <?php echo $form->labelEx($model,'theme'); ?>
                      <?php echo $form->dropDownList($model,'theme', Company::getThemes(), array('class'=>'m-wrap large','prompt'=>'Select Theme')); ?>
                    <?php echo $form->error($model,'theme'); ?>                  
                </div>  
                <?php endif;?>
            </div>
            <div class="row">
                <div class="span5">
                   <?php echo $form->labelEx($model,'name'); ?>
                   <?php echo $form->textField($model,'name',array('class'=>'m-wrap large','size'=>60,'maxlength'=>150)); ?>
                   <?php echo $form->error($model,'name'); ?>   
                </div>  
                <div class="span4">
                    <?php echo $form->labelEx($model,'logo'); ?>
                    <?php echo $form->fileField($model,'logo'); ?><br /><span style="color:#BF0000;"> [ Only Support IMAGE (jpg,gif,png) ]</span>
                    <?php echo $form->error($model,'logo'); ?>
                    <?php echo CHtml::image(Yii::app()->baseUrl.$model->logo,"",array("width"=>50)); ?>     
                </div>    
            </div>
           
            <div class="row">
                <div class="span5">
    				<?php echo $form->labelEx($model,'domain'); ?>
                    <?php echo $form->textField($model,'domain',array('class'=>'m-wrap large','size'=>60,'maxlength'=>150)); ?>
                    <?php echo $form->error($model,'domain'); ?>
                </div>
                <div class="span4">
                    <?php echo $form->labelEx($model,'favicon'); ?>
                    <?php echo $form->fileField($model,'favicon'); ?><br /><span style="color:#BF0000;"> [ Only Support (.ico) ]</span>
                    <?php echo $form->error($model,'favicon'); ?>
                    <?php  echo CHtml::image(Yii::app()->baseUrl.$model->favicon,"",array("width"=>50)); ?>
                </div>
            </div>
            <div class="row">
                 <div class="span5">     
    				<?php echo $form->labelEx($model,'email'); ?>
                    <?php echo $form->textField($model,'email',array('class'=>'m-wrap large','size'=>60,'maxlength'=>150)); ?>
                    <?php echo $form->error($model,'email'); ?>
                </div>
                <div class="span4">

                    <?php echo $form->labelEx($model,'sms_api_key'); ?>
                    <?php echo $form->textField($model,'sms_api_key',array('class'=>'m-wrap large','size'=>60,'maxlength'=>250)); ?>
                    <?php echo $form->error($model,'sms_api_key'); ?>

                </div>
            </div>          
            <div class="row">
                <div class="span5">
                    <?php echo $form->labelEx($model,'detailsinfo'); ?>
                    <?php echo $form->textArea($model,'detailsinfo',array('rows'=>6, 'cols'=>50 ,'style'=>'width:320px !important;')); ?>
                    <?php echo $form->error($model,'detailsinfo'); ?>
                </div>
                <div class="span4">

                    <?php echo $form->labelEx($model,'sms_text'); ?>
                    <?php echo $form->textArea($model,'sms_text',array('rows'=>6, 'cols'=>50 ,'style'=>'width:320px !important;')); ?>
                    <?php echo $form->error($model,'sms_text'); ?>

                    <?php echo $form->labelEx($model,'status'); ?>
                    <?php echo $form->dropDownList($model,'status', Lookup::items('Status'), array('options'=>array(User::STATUS_ACTIVE=>array('selected'=>'selected')),'class'=>'m-wrap large','prompt'=>'Select Status')); ?>
                    <?php echo $form->error($model,'status'); ?>
                </div>

            </div>
		</div>
    </div>
                
    <div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Save' : 'Update', array('class'=>'btn blue')); ?>
    </div>
</div>    
<?php $this->endWidget(); ?>
</div> <!-- form -->   

protected/views/company/_search.php
<?php
/* @var $this CompanyController */
/* @var $model Company */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('class'=>'m-wrap large','size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'orgIdPrefix'); ?>
		<?php echo $form->textField($model,'orgIdPrefix',array('class'=>'m-wrap large','size'=>5,'maxlength'=>5)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('class'=>'m-wrap large','size'=>60,'maxlength'=>150)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'detailsinfo'); ?>
		<?php echo $form->textArea($model,'detailsinfo',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'logo'); ?>
		<?php echo $form->textField($model,'logo',array('class'=>'m-wrap large','size'=>60,'maxlength'=>150)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->dropDownList($model,'status', Lookup::items('Status'), array('options'=>array(User::STATUS_ACTIVE=>array('selected'=>'selected')),'class'=>'m-wrap large','prompt'=>'Select Status')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'crAt'); ?>
		<?php echo $form->textField($model,'crAt',array('class'=>'m-wrap large')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'crBy'); ?>
		<?php echo $form->textField($model,'crBy',array('class'=>'m-wrap large','size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'moAt'); ?>
		<?php echo $form->textField($model,'moAt',array('class'=>'m-wrap large')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'moBy'); ?>
		<?php echo $form->textField($model,'moBy',array('class'=>'m-wrap large','size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/company/_view.php
<?php
/* @var $this CompanyController */
/* @var $data Company */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('orgIdPrefix')); ?>:</b>
	<?php echo CHtml::encode($data->orgIdPrefix); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('detailsinfo')); ?>:</b>
	<?php echo CHtml::encode($data->detailsinfo); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('logo')); ?>:</b>
	<?php echo CHtml::encode($data->logo); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('crAt')); ?>:</b>
	<?php echo CHtml::encode($data->crAt); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('crBy')); ?>:</b>
	<?php echo CHtml::encode($data->crBy); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('moAt')); ?>:</b>
	<?php echo CHtml::encode($data->moAt); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('moBy')); ?>:</b>
	<?php echo CHtml::encode($data->moBy); ?>
	<br />

	*/ ?>

</div>

protected/views/company/admin.php
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>Home
        <i class="icon-angle-right"></i>
    </li>
    <li>
        Settings
        <i class="icon-angle-right"></i>
    </li>
    <li>Company <i class="icon-angle-right"></i></li>
    <li>Manage Company</li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->

<?php CHtml::link('Add Company', array('company/create'), array('class'=>'btn light', 'style'=>'float:right;margin-left:10px;'));?>

<div class="form">
<?php $pageSize=Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']); ?>
<?php $this->widget('bootstrap.widgets.TbExtendedGridView', array(
	'id'=>'company-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
    'type' => 'striped bordered condensed',
    'template' => '{summary}{items}{pager}',
    'pager'=> array('header'=>'','class'=> 'MyLinkPager'),
	'columns'=>array(
		array('header'=>'Sl.',
			 'value'=>'$row+1',
		),
		'orgIdPrefix',
		'name',
		'domain',
		'email',
        array(
            'name' => 'favicon',
            'type' => 'raw',
            'value'=>'CHtml::image(Yii::app()->baseUrl.$data->favicon,"",array("style"=>"width:50px;"))',
        ),
		array('name'=>'logo',
			 'type'=>'raw',
			 'value'=>'CHtml::image(Yii::app()->baseUrl.$data->logo,"",array("style"=>"width:50px;"))',
		),	
		array('name'=>'theme',
			 'value'=>'$data->theme',
			 'filter'=>Company::getThemes(),
		),

		array('name'=>'status',
			 'value'=>'Lookup::item("Status", $data->status)',
			 'filter'=>Lookup::items('Status'),
		),
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=> empty(Yii::app()->user->isSuperAdmin)?'{update}':'{view} {update} {delete}',
            'viewButtonImageUrl' => Yii::app()->theme->baseUrl.'/images/gridview/view.png',
			'updateButtonImageUrl' => Yii::app()->theme->baseUrl.'/images/gridview/update.png',
			'deleteButtonImageUrl' => Yii::app()->theme->baseUrl.'/images/gridview/delete.png',
            'header'=>CHtml::dropDownList('pageSize',
		        $pageSize,
		        array(5=>5,10=>10,20=>20,50=>50,100=>100),
		        array(
		       //
		       // change 'user-grid' to the actual id of your grid!!
		        'onchange'=>
		        "$.fn.yiiGridView.update('company-grid',{ data:{pageSize: $(this).val() }})",
		    )),
		),
	),
)); ?>
</div>

protected/views/company/create.php
<?php
/* @var $this CompanyController */
/* @var $model Company */

$this->breadcrumbs=array(
	'Companies'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Company', 'url'=>array('index')),
	array('label'=>'Manage Company', 'url'=>array('admin')),
);
?>

<h1>Create Company</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/company/index.php
<?php
/* @var $this CompanyController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Companies',
);

$this->menu=array(
	array('label'=>'Create Company', 'url'=>array('create')),
	array('label'=>'Manage Company', 'url'=>array('admin')),
);
?>

<h1>Companies</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/company/update.php
<?php
/* @var $this CompanyController */
/* @var $model Company */

$this->breadcrumbs=array(
	'Companies'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Company', 'url'=>array('index')),
	array('label'=>'Create Company', 'url'=>array('create')),
	array('label'=>'View Company', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Company', 'url'=>array('admin')),
);
?>

<h1>Update Company <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/company/view.php
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>Home
        <i class="icon-angle-right"></i>
    </li>
    <li>Company <i class="icon-angle-right"></i></li>
    <li>Details Company # <?php echo $model->name; ?></li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->
<div class="form">
<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'=>$model,
    'type' => 'striped bordered condensed',
	'attributes'=>array(
		'orgIdPrefix',
		'name',
		'domain',
		'email',
		array(            
			'label'=>'favicon',  
			'type'=>'raw',
			'value'=>CHtml::image(Yii::app()->baseUrl.$model->favicon),
		  ),
		  array(            
			'label'=>'Logo',  
			'type'=>'raw',
            'value'=>CHtml::image(Yii::app()->baseUrl.$model->logo),
		  ),
		'detailsinfo',
		'theme',
		array(            
			'label'=>'Status',  
			'value'=>Lookup::item('Status',$model->status),
		  ),
		'crAt',
		array(            
			'label'=>'Created By',  
			'value'=>$model->crBy0->username,),
		'moAt',
		array(            
			'label'=>'Modified By',  
			'type'=>'raw',
			'value'=> (!empty($model->moBy)) ? $model->moBy0->username : '<font color=#fccacb>Not set</font>'),
	),
)); ?>
</div>