protected/models/UserType.php
<?php
/**
 * This is the model class for table "{{user_type}}".
 *
 * The followings are the available columns in table '{{user_type}}':
 * @property string $id
 * @property string $name
 * @property string $isType
 * @property string $status
 * @property string $crAt
 * @property string $crBy
 * @property string $moAt
 * @property string $moBy
 * @property string $rank
 * The followings are the available model relations:
 * @property User $crBy0
 * @property User $moBy0
 */
class UserType extends CActiveRecord
{
	const STATUS_ACTIVE=1;
	const STATUS_INACTIVE=2;
	
	const TYPE_SUPER_ADMIN=1;
	const TYPE_ADMIN=2;
	const TYPE_CUSTOMER=3;
    const TYPE_SUPPLIER=4;
    const TYPE_DIRECT_GRN=5;
    const TYPE_TMP_WORKER=6;
    const TYPE_GUEST=7;

	/*
	 * Returns the static model of the specified AR class.
	 * @return UserType the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{user_type}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(		
			array('name,status', 'required'),
			array('name', 'unique'),	
			array('name', 'length', 'max'=>50),
			array('status', 'length', 'max'=>11),
			array('crBy, moBy', 'length', 'max'=>20),
			array('isType, rank,crAt, moAt', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id,name,isType,rank,status,crAt,crBy, moAt, moBy', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'orgUsertypes' => array(self::HAS_MANY, 'OrgUsertype', 'usertypeId'),
			'crBy0' => array(self::BELONGS_TO, 'User', 'crBy'),
			'moBy0' => array(self::BELONGS_TO, 'User', 'moBy'),
			'orgUsertypesActions' => array(self::HAS_MANY, 'OrgUsertype', 'usertypeId'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'isType'=>'Type',
			'status' => 'Status',
			'crAt' => 'Create At',
			'crBy' => 'Create By',
			'moAt' => 'Last Modify At',
			'moBy' => 'Last Modify By',
			'rank' => 'Rank',
		);
	}
	public function getUrl()
	{
		return Yii::app()->createUrl('userType/view', array(
			'id'=>$this->id,
			'name'=>$this->name,
		));
	}
	
	/**
	 * This is invoked before the record is saved.
	 * @return boolean whether the record should be saved.
	 */
	protected function beforeSave()
	{
		if(parent::beforeSave())
		{
			if($this->isNewRecord)
			{
				$this->crAt=date("Y-m-d H:i:s");
				$this->crBy=Yii::app()->user->id;
			}
			else{
				$this->moBy=Yii::app()->user->id;
				$this->moAt=date("Y-m-d H:i:s");
			}
			return true;
		}
		else
			return false;
	}

	/**
	 * @param $status
	 * @return array names
	 */
	public static function getUserType($status)
    {      
         return  CHtml::listData(self::model()->findAll(array('condition'=>'status=:status', 'params'=>array(':status'=>$status),'order'=>'name')), 'id', 'name');
    }
	
	// get super user type
	public static function getSuperUserType()
    {      
         $model = self::model()->find(array('condition'=>'isType=:isType AND status=:status', 'params'=>array(':isType'=>self::TYPE_SUPER_ADMIN,':status'=>self::STATUS_ACTIVE)));
         if(!empty($model)) return $model->id;   
    }
	
	// get SUPPLIER user type
	public static function getSupplierType()
    {      
         $model = self::model()->find(array('condition'=>'isType=:isType AND status=:status', 'params'=>array(':isType'=>self::TYPE_SUPPLIER,':status'=>self::STATUS_ACTIVE)));
         if(!empty($model)) return $model->id;   
    }

    // get CUSTOMER user type
    public static function getCustomerType()
    {
        $model = self::model()->find(array('condition'=>'isType=:isType AND status=:status', 'params'=>array(':isType'=>self::TYPE_CUSTOMER,':status'=>self::STATUS_ACTIVE)));
        if(!empty($model)) return $model->id;
    }

    // get Direct GRN user type
    public static function getDirectGrnType()
    {
        $model = self::model()->find(array('condition'=>'isType=:isType AND status=:status', 'params'=>array(':isType'=>self::TYPE_DIRECT_GRN,':status'=>self::STATUS_ACTIVE)));
        if(!empty($model)) return $model->id;
    }

    // get temporary worker user type
    public static function getTemporaryWorkerType()
    {
        $model = self::model()->find(array('condition'=>'isType=:isType AND status=:status', 'params'=>array(':isType'=>self::TYPE_TMP_WORKER,':status'=>self::STATUS_ACTIVE)));
        if(!empty($model)) return $model->id;
    }
	
	// Using Add User,Roles Form
	public static function getUserTypeByIsNotSuperAdmin()
	{    
         return  CHtml::listData(self::model()->findAll(array('condition'=>'isType!=:isType and status=:status',
         													  'params'=>array(':isType'=>self::TYPE_SUPER_ADMIN,':status'=>UserType::STATUS_ACTIVE),
                                                              'order'=>'name')), 'id', 'name');
	}

    // getAllUserIsType
    public static function getAllUserIsType($status)
    {
        return array(
            self::TYPE_CUSTOMER=>'Customer',
            self::TYPE_SUPPLIER=>'Supplier',
            self::TYPE_DIRECT_GRN=>'Direct GRN',
            self::TYPE_TMP_WORKER=>'Temporary Worker',
        );
    }
	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('status',$this->status,true);
		$criteria->compare('crAt',$this->crAt,true);
		$criteria->compare('crBy',$this->crBy,true);
		$criteria->compare('moAt',$this->moAt,true);
		$criteria->compare('moBy',$this->moBy,true);
		$criteria->compare('rank',$this->rank);

		return new CActiveDataProvider(get_class($this), array(
			'pagination'=>array(
				//
				// please check how we get the
				// the pageSize from user's state
				'pageSize'=> Yii::app()->user->getState('pageSize',
				//
				// we have previously set defaultPageSize
				// on the params section of our main.php config file
				Yii::app()->params['defaultPageSize']),
			),
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/UserController.php
<?php
class UserController extends Controller
{
	/**
	 * @return array action filters
	 */
	
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//array('ext.yiibooster.filters.BootstrapFilter - delete')
		);
	}
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionDashboard()
	{
		$this->metaTitle = 'Dashboard';
        $modelCustomerPending = Customer::model()->findAll(array('condition'=>'status = :status',
                                                                'params'=>array(':status' => Customer::STATUS_INACTIVE),
                                                                'order'=>'crAt DESC','limit'=>10,
                                                            ));
        $modelOrderPending = SalesInvoice::model()->findAll(array('condition'=>'status=:status AND isEcommerce=:isEcommerce',
                                                                'params'=>array(':status' => SalesInvoice::STATUS_PROCESSING,':isEcommerce'=>SalesInvoice::IS_ECOMMERCE),
                                                                'order'=>'crAt DESC','limit'=>10,
                                                            ));
		$this->render('dashboard',array(
            'modelCustomerPending'=>$modelCustomerPending,
            'modelOrderPending'=>$modelOrderPending,
        ));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{		
		$msg = '';
		$model = new User;	
		$model->isSupplier = User::IS_NOT_SUPPLIER;	
		$userTypeArr = array();
		
		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
		
			if($model->validate()) 
			{				
				if(!isset($_POST['userTypeId']) && empty($_POST['userTypeId'])) $msg = '<div class="notification note-error"><p>Please select one or more user role !</p></div>';
			    
				$salt = uniqid('',true);
				$model->password = $model->hashPassword($model->password,$salt);
				$model->salt = $salt;
                $model->generateAuthKey();
				$model->conf_password = $model->hashPassword($model->conf_password,$salt);
				$model->totalLoginTime = 0;
				$model->status = User::STATUS_ACTIVE;
				
				if($msg=="" || empty($msg))
				{
					if($model->save())
					{
						foreach($_POST['userTypeId'] as $ur)
						{
							$modelr = new Roles;
							$modelr->userTypeId = $ur;
							$modelr->userId = $model->id;
							$modelr->status = Roles::STATUS_ACTIVE;
							$modelr->save();
						}						
						$msg = '<div class="notification note-success"><p>User Added Successfully</p></div>';
					}
				}
			}
		}

		$this->render('_form',array(
			'model'=>$model,'userTypeArr'=>$userTypeArr,
			'msg'=>$msg,
		));
	}
	
	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$msg = '';
		$model=$this->loadModel($id);
		if(!empty($model->supplierId) && $model->supplierId>0) $model->isSupplier = User::IS_SUPPLIER;
		else $model->isSupplier = User::IS_NOT_SUPPLIER;
		
		// select userType by user
		$userTypeArr = array();
		$userTypeArr = CHtml::listData(Roles::model()->findAll('userId=:userId',array(':userId'=>$id)), 'userTypeId', 'userTypeId');
		
		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->validate()) 
			{
				if(!isset($_POST['userTypeId']) && empty($_POST['userTypeId'])) $msg = '<div class="notification note-error"><p>Please select one or more user role !</p></div>';
				
				$salt = uniqid('',true);		
				$model->password = $model->hashPassword($model->password,$salt);
				$model->salt = $salt;
				$model->conf_password = $model->hashPassword($model->conf_password,$salt);
				
				if($msg=="" || empty($msg))
				{
					if($model->save())
					{
						foreach($_POST['userTypeId'] as $ur)
						{
							if(!in_array($ur,$userTypeArr)) 
							{
								$modelr = new Roles;
								$modelr->userTypeId = $ur;
								$modelr->userId = $model->id;
								$modelr->status = Roles::STATUS_ACTIVE;
								$modelr->save();
							}
						}		
							
						// delete if roles deselected
						foreach($userTypeArr as $cr)
						{
							if(!in_array($cr,$_POST['userTypeId'])) 
							{
								$rolesPk = Roles::model()->find(array('condition'=>'userTypeId=:userTypeId and userId=:userId',
																	  'params'=>array(':userTypeId'=>$cr,':userId'=>$id)));
								if(!empty($rolesPk)) $rolesPk->delete();
							}
						}				
						$msg = '<div class="notification note-success"><p>User Updated Successfully</p></div>';
					}
				}
			}
		}

		$this->render('_form',array(
			'model'=>$model,'userTypeArr'=>$userTypeArr,
			'msg'=>$msg,
		));
	}
	
	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionChangepassword()
	{
		$msg = '';
		$form2 = new UserChangePassword;
    	$find = $this->loadModel(Yii::app()->user->id);   	
    	$form2->oldpass = $find->password;
    	
    	if(isset($find)) 
		{
    		if(isset($_POST['UserChangePassword']))
			{
				$form2->attributes=$_POST['UserChangePassword'];
				$vopass = $form2->verifyoldpass = md5($find->salt.$form2->verifyoldpass);
				
				if($form2->validate()) 
				{
					$salt = uniqid('',true);
					$find->password = $find->hashPassword($form2->password,$salt);
					$find->salt = $salt;	
					User::model()->updateByPk($find->id,array('password'=>$find->password,'salt'=>$find->salt));		
					//$this->redirect(array('view','id'=>$find->id));
					$msg = "Password Changed Successfully";
				}
				else{
					$form2->verifyoldpass = "";
					$form2->password = "";
					$form2->verifyPassword = "";
				}
			} 
    	} 	
		$this->render('changepassword',array('form'=>$form2,'msg'=>$msg));	    	
	}
	
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		// page size drop down changed
		if (isset($_GET['pageSize'])) {
		//
		// pageSize will be set on user's state
		Yii::app()->user->setState('pageSize',(int)$_GET['pageSize']);
		//
		// unset the parameter as it
		// would interfere with pager
		// and repetitive page size change
		unset($_GET['pageSize']);
		}
		
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	public function actionApproveduser()
	{
		$whattodo =  $_POST['whattodo'];
		if($whattodo=="getForm"){
			$id = $_POST['id'];

			$whattodo = '"t"';
			$prevalue = User::model()->findByPk($id);
			
			$str = "<div class='form'  style='min-height:90px;'>";
				$str .= "<form id='update-description' action='' method='post' style='width:90%; '>";
					$str .= "<FIELDSET class='fieldset'>";
						$str .= "<LEGEND class='legend'>Update Information</LEGEND>";
						$str .= "<div class='row'>";
							$str .= "<label for='contDesc' style='width:100%; float:left; text-align:left; '>Status</label>";
							$str .= "<select id='status' name='status' style='width:350px'>";
								if($prevalue->status==1) 
									$str .= "<option value='1' selected='selected' >Active</option>";
								else	
									$str .= "<option value='1'>Active</option>";
								if($prevalue->status==2) 	
									$str .= "<option value='2' selected='selected'>Pending</option>";	
								else
									$str .= "<option value='2'>Pending</option>";	
								if($prevalue->status==3)
									$str .= "<option value='3' selected='selected'>Disable</option>";	
								else 	
									$str .= "<option value='3'>Disable</option>";	
							$str .= "</select>";	
						$str .= "</div>";
	
						$str .= "<div class='row'>&nbsp;</div>";
					$str .= "</FIELDSET>";
					$str .= "<div class='row buttons'>";
						
						$str .= "<input type='button' name='updatebtnreq' value='Update' style='width:100px;' id='updatebtnreq' onClick='approveuser($id,".$whattodo.");'/>";	
						$str .= "<input type='button' name='updatebtnreq' value='Cancel' style='width:100px;' id='closewindow' onClick='approveuser($id,\"CloseWindow\");'/>";	
					$str .= "</div>";
				$str .= "</form>";
			$str .= "</div>";
	
			echo $str;
		}
		else{
			$id = $_POST['id'];
			$status = $_POST['status'];			
			$updateActions =  User::model()->updateByPk($id,array('status'=>$status));
			echo 'Successfully Update ';
		}
	}

	/**

protected/views/user/_form.php
<script type="text/javascript" language="javascript">	
	// JQUERY STARTED
	$(document).ready(function() 
	{
		// switch deo types
		$(".isSupplier").click(function() 
		{
			var type = $(this).val();
			if(type==1) $("#supplierRow").show("slow");
			else $("#supplierRow").hide("slow");
		});
  }); 
</script>
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>Home
        <i class="icon-angle-right"></i>
    </li>
    <li>User Management<i class="icon-angle-right"></i></li>
    <li>User</li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->

<!-- BEGIN FORM-->
<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>true,
)); ?>
<?php echo $form->errorSummary($model); ?>

<?php if(!empty($msg)) echo $msg; else { ?>
<div class="notification note-error">
	<p>All star marked <span class="required">*</span> fields are mandatory, please fill up all mandatory fields.</p>
</div>
<?php } ?>
    
<div class="portlet-body"> 
    <div class="tabbable tabbable-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab_1_1" data-toggle="tab"><?php echo $model->isNewRecord ? 'Add' : 'Update';?> User</a></li>
          
        </ul>
        <div class="tab-content">
			 <div class="tab-pane active" id="tab_1_1">
			<?php 
			if(isset(Yii::app()->user->isSuperAdmin) && Yii::app()->user->isSuperAdmin==1) : ?>
				<div class="row">
					<?php echo $form->labelEx($model,'branchId'); ?>
					<?php echo $form->dropDownList($model,'branchId',Branch::getorg(Branch::STATUS_ACTIVE),array('class'=>"large m-wrap",'empty'=>'Please Select a Store')); ?>
					<?php echo $form->error($model,'branchId'); ?>
				</div>
				<?php else : ?>
				<div class="row">
					<?php echo $form->hiddenField($model,'branchId', array('value'=>Yii::app()->session['branchId'])); ?>
				</div> 
			<?php endif; 
			//if($model->isNewRecord) : ?>
				<div class="row">
					<?php  echo CHtml::label('Assign Role <font style="color:#c24e4e">*</font>','',array('class'=>"control-label")); ?>
					<?php  echo CHtml::dropDownList('userTypeId[]', $userTypeArr, (isset(Yii::app()->user->isSuperAdmin) && Yii::app()->user->isSuperAdmin==1) ? UserType::getUserType(UserType::STATUS_ACTIVE) : UserType::getUserTypeByIsNotSuperAdmin(), array('style'=>'height:200px !important;','id'=>'userTypeId[]','class'=>"large m-wrap",'multiple'=>'multiple'));                                                            
					 ?>              
				</div>
		   <?php //endif; ?>
           
            <div class="row">
                <?php echo $form->labelEx($model,'isSupplier'); ?>
                <?php echo $form->radioButtonList($model,'isSupplier',array(1=>'Yes',2=>'No'),array('class'=>'isSupplier','separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;','style'=>'margin-top:-3px !important;','labelOptions'=>array('style'=>'display:inline;min-width:25px !important;'),'template'=>'{input}&nbsp;{label}')); ?>
                <?php echo $form->error($model,'isSupplier'); ?>
           	</div>
            
            <?php 
				if(!empty($model->supplierId) && $model->supplierId>0) $style = 'style="display:block;"';
				else $style = 'style="display:none;"';
			?>
            
            <div id="supplierRow" class="row" <?php echo $style;?>>
            	<?php echo $form->labelEx($model,'supplierId'); ?>
				 <?php echo $form->dropDownList($model,'supplierId', Supplier::getAllSupplier(Supplier::STATUS_ACTIVE), array('class'=>'m-wrap combo combobox','prompt'=>'Select Supplier')); ?>
                 <?php echo $form->error($model,'supplierId'); ?>
            </div>
			
			<div class="row">
				<?php echo $form->labelEx($model,'username'); ?>
				<?php echo $form->textField($model,'username',array('class'=>'m-wrap large')); ?>
				<?php echo $form->error($model,'username'); ?>
			</div>
			
			<div class="row">
				<?php echo $form->labelEx($model,'password'); ?>
				<?php echo $form->passwordField($model,'password',array('value'=>'','class'=>'m-wrap large')); ?>
				<?php echo $form->error($model,'password'); ?>
			</div>
			<div class="row">
				<?php echo $form->labelEx($model,'conf_password'); ?>		
				<?php echo $form->passwordField($model,'conf_password',array('value'=>'','class'=>'m-wrap large')); ?>
				<?php echo $form->error($model,'conf_password'); ?>
			</div>
			
			<div class="row">
				<?php echo $form->labelEx($model,'status'); ?>
				<?php echo $form->dropDownList($model,'status', Lookup::items('Status'), array('options'=>array(User::STATUS_ACTIVE=>array('selected'=>'selected')),'class'=>'m-wrap large','prompt'=>'Select Status')); ?>
				<?php echo $form->error($model,'status'); ?>
			</div>
        </div>        
    </div>
	<div class="row buttons">
	   <?php echo CHtml::submitButton($model->isNewRecord ? 'Save' : 'Update', array('class'=>'btn blue')); ?>
	</div>
</div>
<?php $this->endWidget(); ?>    
</div>
<!-- form -->

protected/views/user/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'salt'); ?>
		<?php echo $form->textField($model,'salt',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	</FIELDSET>
<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/_view.php
<div class="view">
	<b><?php echo CHtml::encode($data->getAttributeLabel('orgId')); ?>:</b>
	<?php echo CHtml::encode($data->orgid0->name); ?>
	<br />
	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />

</div>

protected/views/user/admin.php
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>Home
        <i class="icon-angle-right"></i>
    </li>
    <li>User Management <i class="icon-angle-right"></i></li>
	<li>User<i class="icon-angle-right"></i></li>
    <li>Manage User</li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->

<div class="form">
    <?php $pageSize=Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']); ?>
    <?php $this->widget('bootstrap.widgets.TbExtendedGridView',array(
        'id'=>'user-grid',
        'dataProvider'=>$model->search(),
        'filter'=>$model,
        'type' => 'striped bordered condensed',
		'template' => '{summary}{items}{pager}',
		'pager'=> array('header'=>'','class'=> 'MyLinkPager'),
        'columns'=>array(
            array(            
                'name'=>'branchId',
                'value'=>'$data->branch->name',
                'filter'=>(isset(Yii::app()->user->isSuperAdmin) && Yii::app()->user->isSuperAdmin==1) ? Branch::getAllorg(): '',
            ),
            'username',
             array(            
                'name'=>'status',             
                'type'=>'raw',
                'value'=>'Lookup::item("Status", $data->status)', 
                'filter'=>Lookup::items("Status"),
                
            ),  
            array(
                //'class'=>'CButtonColumn',
                'class'=>'bootstrap.widgets.TbButtonColumn',
                'header'=>CHtml::dropDownList('pageSize',
                    $pageSize,
                    array(5=>5,10=>10,20=>20,50=>50,100=>100),
                    array(
                   //
                   // change 'user-grid' to the actual id of your grid!!
                    'onchange'=>
                    "$.fn.yiiGridView.update('user-grid',{ data:{pageSize: $(this).val() }})",
                )),
            ),
        ),
    )); ?>
</div>

protected/views/user/changeProfile.php
<?php $this->menu=array(
	array('label'=>'Add User', 'url'=>array('create'),'visible'=>UserRights::getVisibility('user', 'create')),
	array('label'=>'Manage User', 'url'=>array('admin'),'visible'=>UserRights::getVisibility('user', 'admin')),
	array('label'=>'Change Password', 'url'=>array('/user/changepassword'),'visible'=>UserRights::getVisibility('user', 'changepassword')),
	array('label'=>'Change Profile', 'url'=>array('/user/changeProfile'),'visible'=>UserRights::getVisibility('user', 'changeProfile')),
); ?>
<h1>Change Profile</h1>
<!--
<div class="form">
<?php echo CHtml::beginForm(); ?>

	<p class="note" align="right"><?php echo 'Fields with <span class="required">*</span> are required.'; ?></p>
	<?php echo CHtml::errorSummary($form); ?>
	
    <FIELDSET class="fieldset">
    	<LEGEND class="legend">Change Password</LEGEND>
	<div class="row">
		<?php 
		
		echo CHtml::activeLabelEx($form,'verifyoldpass'); ?>
		<?php echo CHtml::activePasswordField($form,'verifyoldpass'); ?>
	</div>
	
	<div class="row">
		<?php echo CHtml::activeLabelEx($form,'password'); ?>
		<?php echo CHtml::activePasswordField($form,'password'); ?>
	</div>
	
	<div class="row">
		<?php echo CHtml::activeLabelEx($form,'verifyPassword'); ?>
		<?php echo CHtml::activePasswordField($form,'verifyPassword'); ?>
	</div>
	</FIELDSET>
	<div class="row submit">
		<?php echo CHtml::submitButton("Save"); ?>
	</div>

<?php echo CHtml::endForm(); ?>
</div><!-- form -->-->

protected/views/user/create.php
<div class="midarea">
    <h1>Add User</h1>
    <?php echo $this->renderPartial('_form', array('model'=>$model,'msg'=>$msg)); ?>
</div>